spring:
  application:
    name: booking

  # Database 설정 (환경 변수가 없으면 localhost:3306, root/root로 동작)
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:flash_sale_booking}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create # 개발 환경에서는 서버 구동 시마다 테이블을 재생성하도록 create로 변경
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # Hibernate가 테이블을 다 만든 후 data.sql을 실행하도록 지연

  # SQL 설정 (더미 데이터 삽입)
  sql:
    init:
      mode: always

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}